---
title: "COVID19 Final Project"
author: "Jared, Matt, Megan"
date: "Spring 2022"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.width=10, 
                      fig.height=6, 
                      fig.align = "center")

 #Load the needed package(s) here
pacman::p_load(tidyverse, COVID19,gridExtra, usmap, rpart, rpart.plot, caret, caTools)
cov19 <- covid19(country = c("US"), level = 2, start = "2020-12-01", end = "2021-06-01")
#Renamed the administrative_area_level_2 to state just for convenience and added three percentage variables
cov19 <- rename(cov19, state = administrative_area_level_2) %>%
  mutate(deathRate = (deaths/confirmed)*100,
         infectionRate = (confirmed/population)*100,
         vaccineRate = (vaccines/population)*100, na.rm = TRUE)

# Change the default theme below:
theme_set(theme_bw())
```

The next section is data cleaning

```{r dataClean, message = FALSE, warning = FALSE}
# total count of cov19 at last day of data
cov19LastDay <- cov19 %>%
  filter(date == "2021-06-01")
# Cov19 by region
cov19South <- cov19 %>% 
  filter(state %in% 
           c('Alabama', 'Florida', 'Georgia', 'Mississippi', 
             'South Carolina','Arkansas', 'Louisiana', 'Oklahoma', 
             'Texas', 'Kentucky', 'North Carolina', 'Tennessee', 'Virginia', 'West Virginia'))
cov19NorthE <- cov19 %>% 
  filter(state %in% 
           c('Connecticut', 'Maine', 'Massachusetts', 'New Hampshire', 
             'Rhode Island', 'Vermont', 'New Jersey', 'New York', 'Pennsylvania',
             'Delaware', 'District of Columbia','Maryland'))
cov19MidW <- cov19 %>%
  filter(state %in%
           c('Iowa', 'Kansas', 'Missouri', 'Nebraska', 'North Dakota', 
             'South Dakota', 'Illinois', 'Indiana', 'Michigan', 'Minnesota', 'Ohio', 'Wisconsin'))
cov19West <- cov19 %>%
  filter(state %in%
           c('California', 'Hawaii', 'Nevada','Oregon', 'Washington','Arizona', 
             'Colorado', 'Idaho', 'Montana', 'New Mexico', 'Utah', 'Wyoming'))
```

The next section is graphing

```{r caseGraph, message = FALSE, warning = FALSE}

# North East plot
northEastPlot <- ggplot(cov19NorthE, aes(x = confirmed, y = deaths, color = state))+
  geom_line()+
  labs(title = "North East Covid19 Cases",
       x = "Confirmed Cases",
       y = "Deaths",
       color = "States")+
  theme(text=element_text(size=6),
        legend.position="bottom")+
  scale_x_continuous(labels = scales::comma)

# South Plot
southPlot <- ggplot(cov19South, aes(x = confirmed, y = deaths, color = state))+
  geom_line()+
  labs(title = "South Covid19 Cases",
       x = "Confirmed Cases",
       y = "Deaths",
       color = "States")+
  theme(text=element_text(size=6),
        legend.position="bottom")+
  scale_x_continuous(labels = scales::comma)
# Midwest plot
midWestPlot <- ggplot(cov19MidW, aes(x = confirmed, y = deaths, color = state))+
  geom_line()+
  labs(title = "Midwest Covid19 Cases",
       x = "Confirmed Cases",
       y = "Deaths",
       color = "States")+
  theme(text=element_text(size=6),
        legend.position="bottom")+
  scale_x_continuous(labels = scales::comma)
# West plot
westPlot <- ggplot(cov19West, aes(x = confirmed, y = deaths, color = state))+
  geom_line()+
  labs(title = "West Covid19 Cases",
       x = "Confirmed Cases",
       y = "Deaths",
       color = "States")+
  theme(text=element_text(size=6),
        legend.position="bottom")+
  scale_x_continuous(labels = scales::comma)
```

Grid arrange of the 4 plots above

```{r graphArrange, message = FALSE, warning = FALSE}

grid.arrange(northEastPlot,midWestPlot, southPlot,westPlot, ncol = 2)

```


Plots for vaccine rate vs death rate and infection rate vs death rate with a grid arrange


```{r averagePlot, message = FALSE, warning = FALSE}

# plot for death rate vs vaccine rate for each day
cov19Average <- cov19 %>% group_by(date) %>%
  summarise(mean(infectionRate, na.rm = TRUE), mean(deathRate, na.rm = TRUE), mean(vaccineRate, na.rm = TRUE))

deathVaccineRatesPlot <- ggplot(cov19Average, aes(x = cov19Average$`mean(vaccineRate, na.rm = TRUE)`, y = cov19Average$`mean(deathRate, na.rm = TRUE)`))+
  geom_line()+
  labs(x = "Vaccine Rate",
       y = "Death Rate",
       title = "Death Rate and Vaccine Rate")

deathInfectionRatesPlot <- ggplot(cov19Average, aes(x = cov19Average$`mean(infectionRate, na.rm = TRUE)`, y = cov19Average$`mean(deathRate, na.rm = TRUE)`))+
  geom_line()+
  labs(x = "Infection Rate",
       y = "Death Rate",
       title = "Death Rate and Infection Rate")


# Grid Arrange of two graphs
grid.arrange(deathInfectionRatesPlot, deathVaccineRatesPlot)
```

Map of US with infection as the value

```{r mapPlot, message = FALSE, warning = FALSE}
#filter out non states

cov19StatesOnly <- cov19 %>% group_by(state) %>% filter(state != "American Samoa", state != "Puerto Rico", state != "Northern Mariana Islands", state != "District of Columbia", state != "Guam", state != "Virgin Islands")

## Map of covid cases

plot_usmap(data = cov19StatesOnly,
           values = 'infectionRate',
           regions = 'state',
           color = "black")+
  scale_fill_continuous(low = 'light blue', high = 'red', limits = c(0,15))+
  labs(fill = "Infection Rate",
       title = "Covid 19 Infection Rate")+
  theme(plot.title = element_text(hjust = .5, size = 16))

```

Plot on infection rate with face coverings and without face coverings


```{r infectionBarChart, message = FALSE, warning = FALSE}

infectionBarChartData <- cov19 %>% 
  group_by(facial_coverings) %>% 
  filter(facial_coverings >= -4, na.rm = TRUE) %>%
  summarise(sum(confirmed))


infectionBarChart <- ggplot(infectionBarChartData, 
                            aes(x = facial_coverings, y = infectionBarChartData$`sum(confirmed)`))+
  geom_col(aes(fill = facial_coverings))+
  scale_y_continuous(labels = scales::comma)+
  labs(x = "Facial Covering Policy",
       y = "Cases",
       title = "Cases And Facial Covering Policy")+
  theme(legend.position = "none")+
  scale_x_continuous(breaks = seq(-5,5,1))
  




infectionBarChart






```
```{r decision tree, message = FALSE, warning = FALSE}

cov19StatesOnly <- cov19StatesOnly %>% mutate(region = NA)

West <- c('California', 'Hawaii', 'Nevada','Oregon', 'Washington','Arizona', 'Colorado', 'Idaho', 'Montana', 'New Mexico', 'Utah', 'Wyoming')

Midwest <-  c('Iowa', 'Kansas', 'Missouri', 'Nebraska', 'North Dakota', 
             'South Dakota', 'Illinois', 'Indiana', 'Michigan', 'Minnesota', 'Ohio', 'Wisconsin')

NorthEast <-  c('Connecticut', 'Maine', 'Massachusetts', 'New Hampshire', 
             'Rhode Island', 'Vermont', 'New Jersey', 'New York', 'Pennsylvania',
             'Delaware', 'District of Columbia','Maryland')

South <- c('Alabama', 'Florida', 'Georgia', 'Mississippi', 
             'South Carolina','Arkansas', 'Louisiana', 'Oklahoma', 
             'Texas', 'Kentucky', 'North Carolina', 'Tennessee', 'Virginia', 'West Virginia')

for(i in 1:nrow(cov19StatesOnly)){
  for(j in 1:length(West)){
    if(cov19StatesOnly$state[i] == West[j]){
      cov19StatesOnly$region[i] <- "West"
    }
  }
  for(j in 1:length(NorthEast)){
    if(cov19StatesOnly$state[i] == NorthEast[j]){
      cov19StatesOnly$region[i] <- "Northeast"
    }
  }
  for(j in 1:length(South)){
    if(cov19StatesOnly$state[i] == South[j]){
      cov19StatesOnly$region[i] <- "South"
    }
  }
  for(j in 1:length(Midwest)){
    if(cov19StatesOnly$state[i] == Midwest[j]){
      cov19StatesOnly$region[i] <- "Midwest"
    }
  }
}

cov19Tree <- cov19StatesOnly %>% select(testing_policy, vaccination_policy, facial_coverings, workplace_closing, school_closing, transport_closing, region)
split <-  sample.split(cov19Tree$region, SplitRatio = 0.75)
trainingCov19 <- subset(cov19Tree, subset = split, select = -state)
testingCov19 <- subset(cov19Tree, subset = !split, select = -state)

testingCov19$region <- as.factor(testingCov19$region)

cov19DT <- rpart(formula = region ~ .,
                     data = trainingCov19,
                     method = "class",
                     parms = list(split = "information"),
                     minsplit = 0, 
                     minbucket = 0,
                     cp = -1)


cov19DTPruned$cptable %>% 
  data.frame() %>% 
  filter(xerror < min(xerror) + 0.006795436)

cov19DTPruned <- prune(cov19DT,
                       cp = .01)

rpart.plot(cov19DTPruned, 
           digits = 4,
           fallen.leaves = TRUE,
           type = 5, 
           extra = 101,
           box.palette = 'BlGnYl',
           shadow.col = 'gray',
           legend.x = NA)


cov19_pred <- predict(object = cov19DTPruned,
                       newdata = testingCov19,
                       type = "class")

cm_cov19 <- 
  confusionMatrix(data = cov19_pred, 
                  reference = testingCov19$region,
                  positive = c("Midwest", "Northeast","West", "South"),
                  dnn = c('predicted', 'actual')) 
```

